services:
  - type: web
    name: skill-swap
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: 10000

      - key: MONGO_URI
        sync: false

      - key: JWT_SECRET_KEY
        sync: false

      - key: STREAM_API_KEY
        sync: false

      - key: STREAM_API_SECRET
        sync: false

      - key: FRONTEND_URL
        sync: false